# Generated by Django 4.2.4 on 2023-09-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('genre', models.CharField(max_length=50)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
