# Generated by Django 4.2.4 on 2023-09-04 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
