# Generated by Django 4.2.4 on 2023-09-04 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newsarticle_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsarticle',
            old_name='description',
            new_name='content',
        ),
    ]
