# Generated by Django 4.2.4 on 2023-09-04 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_rename_description_newsarticle_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticle',
            name='content',
        ),
    ]
