# Generated by Django 4.2.4 on 2023-09-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_rename_published_date_newsarticle_publishedat'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='urlToImage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
