# Generated by Django 4.2.4 on 2023-09-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_newsarticle_urltoimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='author',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
