# Generated by Django 4.2.4 on 2023-09-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_alter_newsarticle_urltoimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='urlToImage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
