# Generated by Django 4.2.4 on 2023-09-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_alter_newsarticle_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticle',
            name='id',
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='uuid',
            field=models.CharField(default='news', max_length=10, primary_key=True, serialize=False),
        ),
    ]
